version: '3.8'

services:
  employeeservice:
    image: ${DOCKER_REGISTRY-}employeeservice
    container_name: employee_service
    restart: always
    build:
      context: EmployeeService
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Database=employee_skills;Username=user;Password=user_password
    volumes:
      - logs_app:/app/Logs
      - ./Logs:/app/Logs
    networks:
      - employee_skill_tracker_network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: employee_skills
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - employee_skill_tracker_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d employee_skills"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  logs_app:

networks:
  employee_skill_tracker_network:
     external: true