version: '3.8'

services:
  employeeservice:
    image: ${DOCKER_REGISTRY-}employeeservice
    container_name: employee_service
    restart: always
    build:
      context: EmployeeService
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Database=employee_skills;Username=user;Password=user_password
    ports:
      - "7073:8080"
      - "7074:8081"
    networks:
      - employee_skill_tracker_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: employee_skills
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - employee_skill_tracker_network
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - employee_skill_tracker_network

volumes:
  postgres_data:

networks:
  employee_skill_tracker_network:
     external: true